### ISSUE TITLE
invalid project structure 

### ISSUE THREAD

**Issue by smarks** [kkorn2019/java_class#7]
current:
java_class-assignmentThree
├── KaylaKornelis-app
│   ├── pom.xml
│   └── src
│       ├── main
│       │   └── java
│       │       └── edu
│       │           └── KaylaKornelis
│       │               └── advancedjava
│       │                   ├── App.java
│       │                   ├── Assignment1
│       │                   │   ├── Author.java
│       │                   │   ├── Book.java
│       │                   │   ├── Genre.java
│       │                   │   └── Title.java
│       │                   ├── Assignment2
│       │                   │   ├── BasicStockService.java
│       │                   │   ├── StockQuote.java
│       │                   │   ├── StockService.java
│       │                   │   └── StockServiceFactory.java
│       │                   └── Assignment3
│       │                       ├── BasicStockService.java
│       │                       ├── StockQuote.java
│       │                       ├── StockQuoteApplication.java
│       │                       ├── StockService.java
│       │                       └── StockServiceFactory.java
│       └── test
│           └── java
│               └── edu
│                   └── KaylaKornelis
│                       └── advancedjava
│                           ├── AppTest.java
│                           ├── Assignment1
│                           │   └── BookTest.java
│                           ├── Assignment2
│                           │   ├── StockQuoteTest.java
│                           │   └── StockServiceFactoryTest.java
│                           └── Assignment3
│                               ├── StockQuoteApplicationTest.java
│                               ├── StockQuoteTest.java
│                               └── StockServiceFactoryTest.java
├── README.md
└── pom.xml

should be:

 >tree java_class-assignmentThree
java_class-assignmentThree
├── README.md
├── pom.xml
└── src
    ├── main
    │   └── java
    │       └── edu
    │           └── KaylaKornelis
    │               └── advancedjava
    │                   ├── App.java
    │                   ├── Assignment1
    │                   │   ├── Author.java
    │                   │   ├── Book.java
    │                   │   ├── Genre.java
    │                   │   └── Title.java
    │                   ├── Assignment2
    │                   │   ├── BasicStockService.java
    │                   │   ├── StockQuote.java
    │                   │   ├── StockService.java
    │                   │   └── StockServiceFactory.java
    │                   └── Assignment3
    │                       ├── BasicStockService.java
    │                       ├── StockQuote.java
    │                       ├── StockQuoteApplication.java
    │                       ├── StockService.java
    │                       └── StockServiceFactory.java
    └── test
        └── java
            └── edu
                └── KaylaKornelis
                    └── advancedjava
                        ├── AppTest.java
                        ├── Assignment1
                        │   └── BookTest.java
                        ├── Assignment2
                        │   ├── StockQuoteTest.java
                        │   └── StockServiceFactoryTest.java
                        └── Assignment3
                            ├── StockQuoteApplicationTest.java
                            ├── StockQuoteTest.java
                            └── StockServiceFactoryTest.java

**Comment by kkorn2019** [comment]
Project structure has been corrected.
